name: Deploy to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Abhängigkeiten installieren
        run: npm ci

      - name: Astro Projekt bauen
        run: npm run build

      - name: AWS Anmeldung via Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Dateien zu S3 hochladen
        run: aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}
